# Generated by Django 3.1.7 on 2021-03-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=500, verbose_name='Slug')),
                ('code_zip', models.TextField(verbose_name='Zip')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.states')),
            ],
        ),
    ]
