# Generated by Django 3.1.7 on 2021-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('rating', models.IntegerField()),
                ('avatar', models.URLField(verbose_name='Avatar')),
            ],
        ),
    ]
